---
title: "Homework 1"
author: "CS 498, Spring 2018, Xiaoming Ji"
date: ''
output:
  html_document:
    toc: yes
  pdf_document: default
---


#Problem 1

You can find a dataset dealing with European employment in 1979 at http://lib.stat.cmu.edu/DASL/Stories/EuropeanJobs.html. This dataset gives the percentage of people employed in each of a set of areas in 1979 for each of a set of European countries. Notice this dataset contains only 26 data points.

##1
Use an agglomerative clusterer to cluster this data. Produce a dendrogram of this data for each of single link, complete link, and group average clustering. 

```{r, message=FALSE}
EuropeanJobs = read_csv("EuropeanJobs.csv")
#head(EuropeanJobs)

plot(hclust(dist(EuropeanJobs[,-1]), method = "single"), labels=EuropeanJobs$Country)
plot(hclust(dist(EuropeanJobs[,-1]), method = "complete"), labels=EuropeanJobs$Country)
plot(hclust(dist(EuropeanJobs[,-1]), method = "average"), labels=EuropeanJobs$Country)
```


We will label the countries on the axis. What structure in the data does each method expose? it's fine to look for code, rather than writing your own. Hint: I made plots I liked a lot using R's hclust clustering function, and then turning the result into a phylogenetic tree and using a fan plot, a trick I found on the web; try plot(as.phylo(hclustresult), type='fan'). You should see dendrograms that "make sense" (at least if you remember some European history), and have interesting differences.

##2
Using k-means, cluster this dataset. What is a good choice of k for this data and why?


#Problem 2
Do exercise 6.2 in the Jan 15 version of the course text