
```{r, echo=FALSE}
wdat<-read.csv('pima-indians-diabetes.data.csv', header=FALSE)
library(klaR)
library(caret)
bigx<-wdat[,-c(9)]
bigy<-wdat[,9]
trscore<-array(dim=10)
tescore<-array(dim=10)
for (wi in 1:10)
{wtd<-createDataPartition(y=bigy, p=.8, list=FALSE)
 nbx<-bigx
 ntrbx<-nbx[wtd, ]
 ntrby<-bigy[wtd]
 trposflag<-ntrby>0
 ptregs<-ntrbx[trposflag, ]
 ntregs<-ntrbx[!trposflag,]
 ntebx<-nbx[-wtd, ]
 nteby<-bigy[-wtd]
 ptrmean<-sapply(ptregs, mean, na.rm=TRUE)
 ntrmean<-sapply(ntregs, mean, na.rm=TRUE)
 ptrsd<-sapply(ptregs, sd, na.rm=TRUE)
 ntrsd<-sapply(ntregs, sd, na.rm=TRUE)
 ptroffsets<-t(t(ntrbx)-ptrmean)
 ptrscales<-t(t(ptroffsets)/ptrsd)
 ptrlogs<--(1/2)*rowSums(apply(ptrscales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ptrsd))
 ntroffsets<-t(t(ntrbx)-ntrmean)
 ntrscales<-t(t(ntroffsets)/ntrsd)
 ntrlogs<--(1/2)*rowSums(apply(ntrscales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ntrsd))
 lvwtr<-ptrlogs>ntrlogs
 gotrighttr<-lvwtr==ntrby
 trscore[wi]<-sum(gotrighttr)/(sum(gotrighttr)+sum(!gotrighttr))
 pteoffsets<-t(t(ntebx)-ptrmean)
 ptescales<-t(t(pteoffsets)/ptrsd)
 ptelogs<--(1/2)*rowSums(apply(ptescales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ptrsd))
 nteoffsets<-t(t(ntebx)-ntrmean)
 ntescales<-t(t(nteoffsets)/ntrsd)
 ntelogs<--(1/2)*rowSums(apply(ntescales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ntrsd))
 lvwte<-ptelogs>ntelogs
 gotright<-lvwte==nteby
 tescore[wi]<-sum(gotright)/(sum(gotright)+sum(!gotright))
}

print(mean(tescore))
```


```{r, echo=FALSE}
wdat<-read.csv('pima-indians-diabetes.data.csv', header=FALSE)
library(klaR)
library(caret)
bigx<-wdat[,-c(9)]
bigy<-wdat[,9]
nbx<-bigx
for (i in c(3, 5, 6, 8))
{vw<-bigx[, i]==0
 nbx[vw, i]=NA
}
trscore<-array(dim=10)
tescore<-array(dim=10)
for (wi in 1:10)
{wtd<-createDataPartition(y=bigy, p=.8, list=FALSE)
 ntrbx<-nbx[wtd, ]
 ntrby<-bigy[wtd]
 trposflag<-ntrby>0
 ptregs<-ntrbx[trposflag, ]
 ntregs<-ntrbx[!trposflag,]
 ntebx<-nbx[-wtd, ]
 nteby<-bigy[-wtd]
 ptrmean<-sapply(ptregs, mean, na.rm=TRUE)
 ntrmean<-sapply(ntregs, mean, na.rm=TRUE)
 ptrsd<-sapply(ptregs, sd, na.rm=TRUE)
 ntrsd<-sapply(ntregs, sd, na.rm=TRUE)
 ptroffsets<-t(t(ntrbx)-ptrmean)
 ptrscales<-t(t(ptroffsets)/ptrsd)
 ptrlogs<--(1/2)*rowSums(apply(ptrscales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ptrsd))
 ntroffsets<-t(t(ntrbx)-ntrmean)
 ntrscales<-t(t(ntroffsets)/ntrsd)
 ntrlogs<--(1/2)*rowSums(apply(ntrscales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ntrsd))
 lvwtr<-ptrlogs>ntrlogs
 gotrighttr<-lvwtr==ntrby
 trscore[wi]<-sum(gotrighttr)/(sum(gotrighttr)+sum(!gotrighttr))
 pteoffsets<-t(t(ntebx)-ptrmean)
 ptescales<-t(t(pteoffsets)/ptrsd)
 ptelogs<--(1/2)*rowSums(apply(ptescales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ptrsd))
 nteoffsets<-t(t(ntebx)-ntrmean)
 ntescales<-t(t(nteoffsets)/ntrsd)
 ntelogs<--(1/2)*rowSums(apply(ntescales,c(1, 2), function(x)x^2), na.rm=TRUE)-sum(log(ntrsd))
 lvwte<-ptelogs>ntelogs
 gotright<-lvwte==nteby
 tescore[wi]<-sum(gotright)/(sum(gotright)+sum(!gotright))
}

print(mean(tescore))
```

```{r}
wdat<-read.csv('pima-indians-diabetes.data.csv', header=FALSE)
library(klaR)
library(caret)
bigx<-wdat[,-c(9)]
bigx2<-apply(bigx, c(1, 2), function(x)x^2)
bigx<-cbind(bigx, bigx2)
errs<-array(dim=3)
cvs<-c(0.005, 0.01, 0.1)
for (wi in c(1, 2, 3))
  {bigy<-as.factor(wdat[,9])
  wtd<-createDataPartition(y=bigy, p=.8, list=FALSE)
  wstring<-paste("-c", sprintf('%f', cvs[wi]), sep=" ")
  svm<-svmlight(bigx[wtd,], bigy[wtd], pathsvm='./svmlight', svm.options=wstring)
  labels<-predict(svm, bigx[-wtd,])
foo<-labels$class
errs[wi]<-sum(foo==bigy[-wtd])/(sum(foo==bigy[-wtd])+sum(!(foo==bigy[-wtd])))
}
```


```{r}
#Stretch image to new size
stretch_image = function(img, new_width, new_height) {
  new_img = apply(img, 2, function(y){return (spline(y, n = new_height)$y)})
  new_img = t(apply(new_img, 1, function(y){return (spline(y, n = new_width)$y)}))

  new_img[new_img < 0] = 0
  new_img = round(new_img)
  
  return (new_img)
}

#Make stretched bounding box
ss_box = function(img, box_width, box_height) {
  col = colSums(img)
  row = rowSums(img)

  #Calculate image boundary  
  top = bottom = left = right  = 0

  for (i in 1:length(row)) {if (row[i] != 0) { top = i; break}}
  for (i in length(row):1) {if (row[i] != 0) { bottom = i; break}}  
  for (i in 1:length(col)) {if (col[i] != 0) { left = i; break}}
  for (i in length(col):1) {if (col[i] != 0) { right = i; break}}

  if(top >= bottom || left >= right){stop("bad image")}
  
  box_img = img[top:bottom, left:right]
  
  top    = (dim(img)[1] - box_height) / 2 + 1
  bottom = top + box_height - 1
  left   = (dim(img)[2] - box_width) / 2 + 1
  right  = left + box_width - 1
  
  #Draw box
  ss_img = array(0, dim(img))
  ss_img[top - 1, (left - 1) : (right + 1)]    = 255
  ss_img[bottom + 1, (left - 1) : (right + 1)] = 255
  ss_img[(top - 1): (bottom + 1), (left - 1)]    = 255
  ss_img[(top - 1): (bottom + 1), (right + 1)]   = 255
  
  ss_img[top:bottom, left:right] = (stretch_image(box_img, box_width, box_height))
  
  #Thresholding
  ss_img[ss_img > 128] = 255
  ss_img[ss_img <= 128] = 0
  
  return (ss_img)
}
```

```{r}
#to.read = file("./MNIST/t10k-images-idx3-ubyte", "rb")
mnist_file = gzfile("./MNIST/t10k-images-idx3-ubyte.gz", "rb")

readBin(mnist_file, integer(), n = 4, endian = "big")

for(i in 1:10000){
  m = matrix(readBin(mnist_file, integer(), size = 1, n = 28*28, endian = "big", signed = FALSE), 28, 28);
  
  box = ss_box(m, 20, 20)
  #image(m[,dim(m)[2]:1], col  = gray((255:0)/255))
  #image(box[,dim(box)[2]:1], col  = gray((255:0)/255))
}

close(mnist_file)
```

```{r}

sb = function(img, box_width, box_height) {
  col = colSums(img)
  row = rowSums(img)

  #Calculate image boundary and extract the bounding image
  top = bottom = left = right  = 0

  for (i in 1:length(row)) {if (row[i] != 0) { top = i; break}}
  for (i in length(row):1) {if (row[i] != 0) { bottom = i; break}}  
  for (i in 1:length(col)) {if (col[i] != 0) { left = i; break}}
  for (i in length(col):1) {if (col[i] != 0) { right = i; break}}

  if(top >= bottom || left >= right){stop("bad image")}
  
  box_img = img[top:bottom, left:right]
  
  
  top    = (dim(img)[1] - box_height) / 2 + 1
  bottom = top + box_height - 1
  left   = (dim(img)[2] - box_width) / 2 + 1
  right  = left + box_width - 1

  ss_img = array(0, dim(img))
  ss_img[top:bottom, left:right] = (stretch_image(box_img, box_width, box_height))
  
  return (ss_img)
}

process_save = function(input_gzfile_name, output_file_name) {
  input_gzfile = file(input_gzfile_name, "rb")
  output_file = file(output_file_name, "wb")

  header = readBin(input_gzfile, integer(), n = 4,  endian = "big")
  writeBin(header, output_file, endian = "big")
  
  sb_images = list()
  original_images = list()
  
  for (i in 1:header[2]) {
    data = readBin(input_gzfile, integer(), size = 1, n = 28*28, endian = "big", 
                   signed = FALSE)
    if(length(data) != 28*28) break
    original_images[[i]] = matrix(data, 28, 28);
    
    sb_images[[i]] = sb(original_images[[i]], 20, 20)
    writeBin(as.integer(sb_images[[i]]), output_file, size = 1)
  }

  close(input_gzfile)
  close(output_file)
}

process_save("./MNIST/train-images-idx3-ubyte", "./MNIST/train-images-idx3-ubyte-sb")
process_save("./MNIST/t10k-images-idx3-ubyte", "./MNIST/t10k-images-idx3-ubyte-sb")
```

